const Actions = {
    ADD_LIST_SUCCESS: "ADD_LIST_SUCCESS",
    ADD_LIST_ERROR: "ADD_LIST_ERROR",
    DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
    DELETE_LIST_ERROR: "DELETE_LIST_ERROR",
    SELECT_LIST: "SELECT_LIST",
    GET_ALL_LISTS_SUCCESS: "GET_ALL_LISTS_SUCCESS",
    GET_ALL_LISTS_ERROR: "GET_ALL_LISTS_ERROR",
    GET_TODAY_SUCCESS: "GET_TODAY_SUCCESS",
    GET_TODAY_ERROR: "GET_TODAY_ERROR",
    GET_NUMBER_OPENED_TODO_SUCCESS: "SET_NUMBER_OPENED_TODO__SUCCESS",
    GET_NUMBER_OPENED_TODO_ERROR: "SET_NUMBER_OPENED_TODO__ERROR"

}

export default Actions;