const Actions = {
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_ERROR: "ADD_TODO_ERROR",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    DELETE_TODO_ERROR: "DELETE_TODO_ERROR",
    TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS",
    TOGGLE_TODO_ERROR: "TOGGLE_TODO_ERROR",
    GET_ALL_TODO_SUCCESS: "GET_ALL_TODO_SUCCESS",
    GET_ALL_TODO_ERROR: "GET_ALL_TODO_ERROR"
}

export default Actions;